---
# See http://mumble-ruby-pluginbot.readthedocs.io/en/master/explain_the_config.html for the documentation of this config file.

# IMPORTANT: Please read http://mumble-ruby-pluginbot.rtfd.io/en/devel/explain_the_config.html#default-configuration-and-override-configuration to understand how this override configuration works.

debug: true
language: en

main:
  logfile: "/home/botmaster/logs/bot1.log"
  ducking: false
  automute_if_alone: true
  stop_on_unregistered: true
  whitelist_enabled: false
  control:
    string: "."
    message:
      private_only: false
      registered_only: true
    historysize: 20
  fifo: "/home/botmaster/mpd1/mpd.fifo"
  user:
    whitelisted: # See http://mumble-ruby-pluginbot.rtfd.io/en/master/explain_the_config.html#main-user-whitelisted
    superuser: # See http://mumble-ruby-pluginbot.rtfd.io/en/master/explain_the_config.html#main-user-superuser
    banned: # See http://mumble-ruby-pluginbot.rtfd.io/en/master/explain_the_config.html#main-user-banned
    bound: # See http://mumble-ruby-pluginbot.rtfd.io/en/master/explain_the_config.html#main-user-bound

mumble:
  use_vbr: 1
  bitrate: 72000
  host: m.natenom.com
  port: 64738
  name: MumbleRubyPluginbot
  password: ''
  channel: Bottest

plugin:
  mpd:
    volume: 65
    host: localhost
    port: 7701
    password: ''
  idle:
    maxidletime: 600
    idleaction: 'channel'
